apiVersion: v1
kind: Service
metadata:
  name: {{ include "greet.fullname" . }}
  labels:
    {{- include "greet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # number or name need to validate best practices
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "greet.selectorLabels" . | nindent 4 }}
